### PR TITLE
Replace img2gb with rgbgfx+xxd and ihx2gb with makebin+rgbfix

### PR DESCRIPTION
**Pull request by basxto**
I wasn't able to get `img2gb` running and since the tools were there, I also replaced `ihx2gb`.

This introduces external dependencies:  rgbds (rgbgfx and rgbfix), xxd (.2bpp⇒.c)

It does not create a .sym file for the ROM, but that should be possible with the next SDCC release soon.

With SDCC 4.0.0 this makes the ROM 380 bytes smaller than https://donaldhays.com/projects/bubble-factory/play/bin/BubbleFactory.gb

Current snapshot again makes it 659 bytes smaller compared to 4.0.0

### CODE REVIEW

**Comment by DonaldHays** [comment]
Sorry for the delay in responding!

I'm not currently inclined to accept this pull request. I did a clean checkout of the project (from the main branch, not this pull request) and followed the build instructions, using SDCC 4.0 in the process. I was able to build the game successfully. The fix for `img2gb` seems to have been all that was really needed to repair the build process. If there was no reasonable fix for `img2gb`, I think I would weigh this PR more favorably, but as-is it kind of just adds additional dependencies.

There's definitely merit to being able to remove code, since the easiest line of code to maintain is the line of code you don't even have, but this is more of a code dump of an old project, rather than a living project, and so while I'm willing to make minimal changes to keep it building, I'm not as interested in going much further.

Thank you for reporting the issue with `img2gb`, though!

**Comment by basxto** [comment]
It does not justify new dependencies (rgbds, xxd) anymore.

I'll PR the parts again, which introduce a variable for SDCC's location, so that it is easier to build with a globally installed SDCC.

I planned to replace `node ../ihx2gb --name BUBBLEFACT --licensee DH --cartridge 9 --ram 1 $< $@` with makebin, which is bundled with sdcc `$(MKROM) -Z -yn BUBBLEFACT -yk DH -yt 9 -ya 1 -yS $< $@` once 4.1.0 is released, should I leave that out then?

**Comment by DonaldHays** [comment]
Both of those sound really awesome to me, yeah!

I'm not sure why I liked putting copies of compilers in my Game Boy project directories at the time, but it definitely goes against the grain of usual practice, and I didn't like that part much when I rebuilt it yesterday. Using a globally-installed SDCC makes more sense. I don't know what platform you're using, but for macOS I would include a note recommending using the command `brew install sdcc` to easily install SDCC.

Once 4.1.0 is released, I think `makebin` will make a ton of sense. It'll be present in the already-available SDCC dependency, it won't lose anything (since it'll be able to generate a SYM at that point), and it'll permit deleting the `ihx2gb` tool.

**Comment by basxto** [comment]
I totally forgot about this.
Now this gem becomes pretty interesting for testing the coming 4.2.0 with it’s new calling convention. That  will certainly break inline assembly functions.

**Pull request closed without merging**
